[workspace]
authors = ["Rishabh Ranjan <rishabhranjan0207@gmail.com>"]
channels = ["conda-forge"]
name = "relbench"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
uv = "*"
python = "==3.10"

[pypi-options]
index-url = "https://pypi.org/simple"
find-links = [{ url = "https://data.pyg.org/whl/torch-2.7.0+cu126.html" }]

[pypi-dependencies]
pyg-lib = "*"
relbench = { path = ".", editable = true, extras = ["full", "example", "dev", "test"] }

[tasks.test]
cmd = "pytest test/base test/datasets"
