[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "relbench"
version = "0.2.0"
description = "RelBench: Relational Deep Learning Benchmark"
authors = [{name = "RelBench Team", email = "relbench@cs.stanford.edu"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
	"License :: OSI Approved :: MIT License",
]
requires-python=">=3.8"
keywords=[]
dependencies=[
	"pandas",
	"pooch",
	"pyarrow",
	"numpy==1.26.0",
	"duckdb",
	"requests",
	"tqdm",
	"scikit-learn",
	"typing-extensions",
	"matplotlib",
	"networkx",
]

[project.optional-dependencies]
example=[
	"torch",
	"pytorch_frame>=0.2.2",
	"torch_geometric",
	"faiss-cpu",
	"sentence-transformers",
	"tensorboard",
]
test=[
	"pytest",
]
dev=[
	"pre-commit",
]

[project.urls]
Home = "https://relbench.stanford.edu"

[tool.flit.module]
name="relbench"

[tool.pytest.ini_options]
addopts = [
	"--capture=no",
	"--color=yes",
	"-vv",
]
