torch_frame_model:
  channels: 128
  num_layers: 2
model:
  channels: 128
  aggr: "sum"
  conv: "sage"
  num_layers: 2
  use_self_join: true
  node_type_considered: ["customer"]
dataset:
  name: "rel-amazon"
  cache_dir: "/dfs/scratch0/joshrob/projects/relbench/cache"
  root_dir: "/dfs/scratch0/joshrob/projects/relbench/data"
  task: "rel-amazon-churn"
  # All tasks:
  # rel-stackex: rel-stackex-engage, rel-stackex-votes, rel-stackex-badges
  # rel-amazon: rel-amazon-churn, rel-amazon-ltv, rel-amazon-product-churn, rel-amazon-product-ltv
loader:
  num_neighbors: 128
  num_workers: 1
  batch_size: 512
optim:
  max_epoch: 30
  early_stop: 10
  base_lr: 0.01
seed: 42
