torch_frame_model:
  channels: 128
  num_layers: 2
model:
  channels: 128
  aggr: "sum"
  conv: "sage"
  num_layers: 2
  use_self_join: false
  dropout: 0.0
dataset:
  name: "rel-f1"
  cache_dir: "/dfs/scratch0/joshrob/projects/relbench/cache"
  root_dir: "/dfs/scratch0/joshrob/projects/relbench/data"
  task: "rel-f1-dnf"
  # All tasks:
  # rel-stackex: rel-stackex-engage, rel-stackex-votes, rel-stackex-badges
  # rel-amazon: rel-amazon-churn, rel-amazon-ltv, rel-amazon-product-churn, rel-amazon-product-ltv
  # rel-f1: rel-f1-position, rel-f1-dnf, rel-f1-qualifying
loader:
  num_neighbors: 128
  num_workers: 1
  batch_size: 512
  temporal_strategy: 'uniform'
optim:
  max_epoch: 50
  early_stop: 10
  base_lr: 0.01
seed: 42
