torch_frame_model:
  channels: 128
  num_layers: 2
model:
  channels: 128
  aggr: "sum"
  conv: "sage"
  num_layers: 2
  use_self_join: true
  use_self_join_with_retrieval: false
  perturb_edges: null
  feature_dropout: null
selfjoin:
  node_type_considered: 'drivers'
  num_filtered: 20
  sim_score_type: 'L2'  # 'cos', 'L2', 'attention'
  aggr_scheme: 'mpnn'  # 'gat', 'mpnn'
  normalize_score: true
  aggr: 'sum'
dataset:
  name: "rel-f1"
  cache_dir: "/dfs/scratch0/jiaqihan/projects/relbench/cache"
  root_dir: "/dfs/scratch0/jiaqihan/projects/relbench/data"
  task: "rel-f1-qualifying"
  # All tasks:
  # rel-stackex: rel-stackex-engage, rel-stackex-votes, rel-stackex-badges
  # rel-amazon: rel-amazon-churn, rel-amazon-ltv, rel-amazon-product-churn, rel-amazon-product-ltv
  # rel-f1: rel-f1-position, rel-f1-dnf, rel-f1-qualifying
loader:
  num_neighbors: 128
  num_workers: 1
  batch_size: 512
  temporal_strategy: 'uniform'
optim:
  max_epoch: 30
  early_stop: 10
  base_lr: 0.01
seed: 42
